In [7]:
import numpy as np
a = np.array([1,3,5,6,3,4,56,6,'Hello',"world",1.322,True,{"hello":'World'}])
print (a)
for i in a:
    print (i, "is a ",type(i))

[1 3 5 6 3 4 56 6 'Hello' 'world' 1.322 True {'hello': 'World'}]
1 is a  <class 'int'>
3 is a  <class 'int'>
5 is a  <class 'int'>
6 is a  <class 'int'>
3 is a  <class 'int'>
4 is a  <class 'int'>
56 is a  <class 'int'>
6 is a  <class 'int'>
Hello is a  <class 'str'>
world is a  <class 'str'>
1.322 is a  <class 'float'>
True is a  <class 'bool'>
{'hello': 'World'} is a  <class 'dict'>


In [10]:
import numpy as np 
a = np.array(range(1,20))
print (a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [11]:
import numpy as np
a = np.arange(1,20)
print (a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [13]:
import numpy as np
list = [2,4,5,6,2]
for i in list:
    b = np.array(range(i,i+3))
    print (b)

[2 3 4]
[4 5 6]
[5 6 7]
[6 7 8]
[2 3 4]


In [14]:
import numpy as np
a = np.arange(0,22,2)
print (a)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [20]:
import numpy as np
a = np.linspace(0,10,5)
print (a)

[ 0.   2.5  5.   7.5 10. ]


In [25]:
import numpy as np
a = np.random.random((3,3))
print (a)

[[0.71873813 0.22678783 0.64602241]
 [0.85473137 0.36798971 0.82526096]
 [0.78113621 0.84989332 0.1384782 ]]


In [36]:
import numpy as np
a = np.eye(122)
print (a)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
import numpy as np 
a = np.linspace(0,20,5)
print (a)

[ 0.  5. 10. 15. 20.]


TypeError: Cannot interpret '3' as a data type